# ---
# CKAD Study Topic: apiVersion
# ---
apiVersion: apps/v1

# ---
# CKAD Study Topic: kind
# ---
kind: Deployment

# ---
# CKAD Study Topic: metadata
# ---
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app

# ---
# CKAD Study Topic: spec
# ---
spec:
  # ---
  # CKAD Study Topic: replicas
  # ---
  replicas: 3

  # ---
  # CKAD Study Topic: selector
  # ---
  selector:
    matchLabels:
      app: flask-app

  # ---
  # CKAD Study Topic: template
  # ---
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        # ---
        # CKAD Study Topic: Define your app, container, and image
        # ---
        - name: flask-app-container
          # ---
          # We're back to the simple image name!
          # Rancher Desktop will find this local image.
          # ---
          image: my-flask-app:v1

          # ---
          # 'IfNotPresent' is the correct policy.
          # The 'rdctl' command (step 2) will ensure
          # the image IS present in the cluster's cache.
          # ---
          imagePullPolicy: IfNotPresent

          # ---
          # Day 3: Injecting ConfigMaps
          # ---
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: flask-app-config
                  key: WELCOME_MESSAGE

          ports:
            - containerPort: 5000

